### ISSUE TITLE
Observer actor

### ISSUE THREAD

**Issue by zhenik** [sysco-middleware/kafka-topic-metadata#4]
As an idea, to have Kafka-topic-observer actor. 

[EXAMPLE](https://github.com/sysco-middleware/kafka-topic-metadata/blob/master/tmetadata/src/main/scala/no/sysco/middleware/kafka/tmetadata/application/KafkaTopicsObserverActor.scala)

This actor will be scheduled to do its job in the background.

1. Observe for changes (create, update, delete) Kafka topics. And update their metadata.

This actor allows avoiding manual creating metadata, the only `manual` update of metadata will be available via interfaces (REST, GraphQL, gRPC, etc. . .)

example rest `PUT topics/{topic_name}`

**Comment by zhenik** [comment]
I described approach [here](https://www.lucidchart.com/invitations/accept/569a9c5a-0bfd-4cd5-8577-63a9b91ef229)

**Comment by jeqo** [comment]
@NikitaZhevnitskiy, I like the approach. It can increase usability by reducing steps to document topics.

We can consider this one as part of the initial release.

I will close this as accepted.
