### ISSUE TITLE
Consider to use GlobalKTable

### ISSUE THREAD

**Issue by zhenik** [sysco-middleware/kafka-topic-metadata#8]
Can be helpful [org.apache.kafka.streams.kstream.GlobalKTable<K,V>](http://kafka.apache.org/20/javadoc/org/apache/kafka/streams/kstream/GlobalKTable.html)

**Comment by jeqo** [comment]
Closing this in favor of https://github.com/sysco-middleware/kafka-steward. It will be consider on the design.
